export const arvorearSpaceAssets = {
  hero: {
    recepcao: "/assets/arvorear/espaco/hero/hero-recepcao-real-16x9.webp",
    fachada: "/assets/arvorear/espaco/hero/hero-fachada-real-wide.webp",
    patio: "/assets/arvorear/espaco/hero/hero-frente-patio-wide.webp",
    cardRecepcao: "/assets/arvorear/espaco/hero/card-recepcao-logo-4x5.webp",
  },
  galeria: [
    { src: "/assets/arvorear/espaco/recepcao/recepcao-logo-balcao-close.webp", alt: "Close da recepção da Clínica Arvorear com balcão branco, parede verde e logo da marca.", category: "recepcao" },
    { src: "/assets/arvorear/espaco/ambientes/sala-espera-nuvens-cinza.webp", alt: "Sala de espera com poltronas, parede cinza texturizada e detalhe de nuvens no teto.", category: "ambientes" },
    { src: "/assets/arvorear/espaco/detalhes/teto-arvore-iluminada.webp", alt: "Detalhe do teto com copa de árvore iluminada na Clínica Arvorear.", category: "detalhes" },
    { src: "/assets/arvorear/espaco/ambientes/corredor-portas-coloridas-vertical.webp", alt: "Corredor infantil da Clínica Arvorear com portas coloridas e elementos lúdicos nas paredes.", category: "ambientes" },
    { src: "/assets/arvorear/espaco/detalhes/mural-infantil-nuvens-arvore.webp", alt: "Mural infantil com árvores, nuvens e cores suaves no espaço da Clínica Arvorear.", category: "detalhes" },
    { src: "/assets/arvorear/espaco/recepcao/recepcao-logo-arvore.webp", alt: "Recepção da Clínica Arvorear com balcão ripado, parede verde, logo e árvore cenográfica.", category: "recepcao" },
    { src: "/assets/arvorear/espaco/recepcao/recepcao-ampla-balcao-escada.webp", alt: "Vista ampla da recepção da Clínica Arvorear com árvore cenográfica, balcão e sala de espera.", category: "recepcao" },
    { src: "/assets/arvorear/espaco/ambientes/sala-terapia-motora.webp", alt: "Sala de terapia com tatame verde, equipamentos e parede de escalada infantil.", category: "ambientes" },
    { src: "/assets/arvorear/espaco/ambientes/sala-acolhimento-sofa.webp", alt: "Sala de atendimento com sofá, decoração suave e iluminação natural.", category: "ambientes" },
    { src: "/assets/arvorear/espaco/ambientes/sala-acolhimento-poltrona.webp", alt: "Sala acolhedora com poltrona, mesa lateral e quadros decorativos.", category: "ambientes" },
    { src: "/assets/arvorear/espaco/ambientes/sala-musical-teclado.webp", alt: "Sala com teclado e elementos terapêuticos para atividades lúdicas e musicais.", category: "ambientes" },
    { src: "/assets/arvorear/espaco/ambientes/sala-infantil-arcoiris.webp", alt: "Sala infantil com tapete de arco-íris, mesa, cadeiras e parede delicada.", category: "ambientes" },
    { src: "/assets/arvorear/espaco/ambientes/sala-atendimento-mesa-planta.webp", alt: "Sala de atendimento com mesa infantil, prateleiras e plantas suspensas.", category: "ambientes" },
    { src: "/assets/arvorear/espaco/ambientes/sala-ludica-casinha.webp", alt: "Sala lúdica com desenho de casinha, mesa infantil e tapete floral.", category: "ambientes" },
    { src: "/assets/arvorear/espaco/ambientes/corredor-portas-coloridas-panoramico-01.webp", alt: "Vista panorâmica do corredor com portas coloridas e ilustrações de árvores.", category: "ambientes" },
    { src: "/assets/arvorear/espaco/ambientes/corredor-portas-coloridas-panoramico-02.webp", alt: "Corredor panorâmico com portas coloridas e ilustrações lúdicas nas paredes.", category: "ambientes" },
    { src: "/assets/arvorear/espaco/fachada/entrada-escada-logo.webp", alt: "Entrada interna com escada e logo da Arvorear na parede.", category: "fachada" },
    { src: "/assets/arvorear/espaco/fachada/fachada-principal.webp", alt: "Fachada externa da Clínica Arvorear com muro ilustrado e identidade visual.", category: "fachada" },
    { src: "/assets/arvorear/espaco/fachada/frente-patio-brinquedos.webp", alt: "Área externa da Clínica Arvorear com fachada, pátio e brinquedos.", category: "fachada" },
  ],
} as const;
